// This file is auto-generated by @hey-api/openapi-ts

export const AddClientRequestModelSchema = {
    required: ['name', 'origin'],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        origin: {
            type: 'string'
        },
        previewUrlPath: {
            type: 'string',
            nullable: true
        },
        publishedUrlPath: {
            type: 'string',
            nullable: true
        },
        culture: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const AddFilterRequestModelSchema = {
    required: ['filterMatchType', 'name', 'primitiveFieldType', 'propertyAliases'],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        propertyAliases: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        filterMatchType: {
            '$ref': '#/components/schemas/FilterMatchType'
        },
        primitiveFieldType: {
            '$ref': '#/components/schemas/PrimitiveFieldType'
        }
    },
    additionalProperties: false
} as const;

export const AddSortRequestModelSchema = {
    required: ['name', 'primitiveFieldType', 'propertyAlias'],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        propertyAlias: {
            type: 'string'
        },
        primitiveFieldType: {
            '$ref': '#/components/schemas/PrimitiveFieldType'
        }
    },
    additionalProperties: false
} as const;

export const ClientViewModelSchema = {
    required: ['id', 'name', 'origin'],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        origin: {
            type: 'string'
        },
        previewUrlPath: {
            type: 'string',
            nullable: true
        },
        publishedUrlPath: {
            type: 'string',
            nullable: true
        },
        culture: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const EventMessageTypeModelSchema = {
    enum: ['Default', 'Info', 'Error', 'Success', 'Warning'],
    type: 'string'
} as const;

export const FilterMatchTypeSchema = {
    enum: ['Exact', 'Partial'],
    type: 'string'
} as const;

export const FilterViewModelSchema = {
    required: ['alias', 'fieldName', 'filterMatchType', 'id', 'name', 'primitiveFieldType', 'propertyAliases'],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        alias: {
            type: 'string'
        },
        fieldName: {
            type: 'string'
        },
        primitiveFieldType: {
            '$ref': '#/components/schemas/PrimitiveFieldType'
        },
        propertyAliases: {
            type: 'array',
            items: {
                type: 'string'
            }
        },
        filterMatchType: {
            '$ref': '#/components/schemas/FilterMatchType'
        }
    },
    additionalProperties: false
} as const;

export const NotificationHeaderModelSchema = {
    required: ['category', 'message', 'type'],
    type: 'object',
    properties: {
        message: {
            type: 'string'
        },
        category: {
            type: 'string'
        },
        type: {
            '$ref': '#/components/schemas/EventMessageTypeModel'
        }
    },
    additionalProperties: false
} as const;

export const OverviewViewModelSchema = {
    required: ['canAddFilter', 'canAddSort', 'filters', 'sorts'],
    type: 'object',
    properties: {
        filters: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/FilterViewModel'
                    }
                ]
            }
        },
        sorts: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/SortViewModel'
                    }
                ]
            }
        },
        canAddFilter: {
            type: 'boolean'
        },
        canAddSort: {
            type: 'boolean'
        }
    },
    additionalProperties: false
} as const;

export const PrimitiveFieldTypeSchema = {
    enum: ['String', 'Number', 'Date'],
    type: 'string'
} as const;

export const SortViewModelSchema = {
    required: ['alias', 'fieldName', 'id', 'name', 'primitiveFieldType', 'propertyAlias'],
    type: 'object',
    properties: {
        id: {
            type: 'string',
            format: 'uuid'
        },
        name: {
            type: 'string'
        },
        alias: {
            type: 'string'
        },
        fieldName: {
            type: 'string'
        },
        primitiveFieldType: {
            '$ref': '#/components/schemas/PrimitiveFieldType'
        },
        propertyAlias: {
            type: 'string'
        }
    },
    additionalProperties: false
} as const;

export const UpdateClientRequestModelSchema = {
    required: ['name', 'origin'],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        origin: {
            type: 'string'
        },
        previewUrlPath: {
            type: 'string',
            nullable: true
        },
        publishedUrlPath: {
            type: 'string',
            nullable: true
        },
        culture: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const UpdateFilterRequestModelSchema = {
    required: ['name', 'propertyAliases'],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        propertyAliases: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    additionalProperties: false
} as const;

export const UpdateSortRequestModelSchema = {
    required: ['name', 'propertyAlias'],
    type: 'object',
    properties: {
        name: {
            type: 'string'
        },
        propertyAlias: {
            type: 'string'
        }
    },
    additionalProperties: false
} as const;