// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { PostUmbracoManagementApiV1NoCodeDeliveryApiClientData, PostUmbracoManagementApiV1NoCodeDeliveryApiClientError, PostUmbracoManagementApiV1NoCodeDeliveryApiClientResponse, GetUmbracoManagementApiV1NoCodeDeliveryApiClientError, GetUmbracoManagementApiV1NoCodeDeliveryApiClientResponse, DeleteUmbracoManagementApiV1NoCodeDeliveryApiClientByIdData, DeleteUmbracoManagementApiV1NoCodeDeliveryApiClientByIdError, DeleteUmbracoManagementApiV1NoCodeDeliveryApiClientByIdResponse, PutUmbracoManagementApiV1NoCodeDeliveryApiClientByIdData, PutUmbracoManagementApiV1NoCodeDeliveryApiClientByIdError, PutUmbracoManagementApiV1NoCodeDeliveryApiClientByIdResponse, GetUmbracoManagementApiV1NoCodeDeliveryApiQueryError, GetUmbracoManagementApiV1NoCodeDeliveryApiQueryResponse, PostUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterData, PostUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterError, PostUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterResponse, DeleteUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterByIdData, DeleteUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterByIdError, DeleteUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterByIdResponse, PutUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterByIdData, PutUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterByIdError, PutUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterByIdResponse, PostUmbracoManagementApiV1NoCodeDeliveryApiQuerySortData, PostUmbracoManagementApiV1NoCodeDeliveryApiQuerySortError, PostUmbracoManagementApiV1NoCodeDeliveryApiQuerySortResponse, DeleteUmbracoManagementApiV1NoCodeDeliveryApiQuerySortByIdData, DeleteUmbracoManagementApiV1NoCodeDeliveryApiQuerySortByIdError, DeleteUmbracoManagementApiV1NoCodeDeliveryApiQuerySortByIdResponse, PutUmbracoManagementApiV1NoCodeDeliveryApiQuerySortByIdData, PutUmbracoManagementApiV1NoCodeDeliveryApiQuerySortByIdError, PutUmbracoManagementApiV1NoCodeDeliveryApiQuerySortByIdResponse } from './types.gen';

export const client = createClient(createConfig());

export class ClientsService {
    public static postUmbracoManagementApiV1NoCodeDeliveryApiClient<ThrowOnError extends boolean = false>(options?: Options<PostUmbracoManagementApiV1NoCodeDeliveryApiClientData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUmbracoManagementApiV1NoCodeDeliveryApiClientResponse, PostUmbracoManagementApiV1NoCodeDeliveryApiClientError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/client'
        });
    }
    
    public static getUmbracoManagementApiV1NoCodeDeliveryApiClient<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoManagementApiV1NoCodeDeliveryApiClientResponse, GetUmbracoManagementApiV1NoCodeDeliveryApiClientError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/client'
        });
    }
    
    public static deleteUmbracoManagementApiV1NoCodeDeliveryApiClientById<ThrowOnError extends boolean = false>(options: Options<DeleteUmbracoManagementApiV1NoCodeDeliveryApiClientByIdData, ThrowOnError>) {
        return (options?.client ?? client).delete<DeleteUmbracoManagementApiV1NoCodeDeliveryApiClientByIdResponse, DeleteUmbracoManagementApiV1NoCodeDeliveryApiClientByIdError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/client/{id}'
        });
    }
    
    public static putUmbracoManagementApiV1NoCodeDeliveryApiClientById<ThrowOnError extends boolean = false>(options: Options<PutUmbracoManagementApiV1NoCodeDeliveryApiClientByIdData, ThrowOnError>) {
        return (options?.client ?? client).put<PutUmbracoManagementApiV1NoCodeDeliveryApiClientByIdResponse, PutUmbracoManagementApiV1NoCodeDeliveryApiClientByIdError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/client/{id}'
        });
    }
    
}

export class QueryingService {
    public static getUmbracoManagementApiV1NoCodeDeliveryApiQuery<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoManagementApiV1NoCodeDeliveryApiQueryResponse, GetUmbracoManagementApiV1NoCodeDeliveryApiQueryError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/query'
        });
    }
    
    public static postUmbracoManagementApiV1NoCodeDeliveryApiQueryFilter<ThrowOnError extends boolean = false>(options?: Options<PostUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterResponse, PostUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/query/filter'
        });
    }
    
    public static deleteUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterById<ThrowOnError extends boolean = false>(options: Options<DeleteUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterByIdData, ThrowOnError>) {
        return (options?.client ?? client).delete<DeleteUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterByIdResponse, DeleteUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterByIdError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/query/filter/{id}'
        });
    }
    
    public static putUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterById<ThrowOnError extends boolean = false>(options: Options<PutUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterByIdData, ThrowOnError>) {
        return (options?.client ?? client).put<PutUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterByIdResponse, PutUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterByIdError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/query/filter/{id}'
        });
    }
    
    public static postUmbracoManagementApiV1NoCodeDeliveryApiQuerySort<ThrowOnError extends boolean = false>(options?: Options<PostUmbracoManagementApiV1NoCodeDeliveryApiQuerySortData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUmbracoManagementApiV1NoCodeDeliveryApiQuerySortResponse, PostUmbracoManagementApiV1NoCodeDeliveryApiQuerySortError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/query/sort'
        });
    }
    
    public static deleteUmbracoManagementApiV1NoCodeDeliveryApiQuerySortById<ThrowOnError extends boolean = false>(options: Options<DeleteUmbracoManagementApiV1NoCodeDeliveryApiQuerySortByIdData, ThrowOnError>) {
        return (options?.client ?? client).delete<DeleteUmbracoManagementApiV1NoCodeDeliveryApiQuerySortByIdResponse, DeleteUmbracoManagementApiV1NoCodeDeliveryApiQuerySortByIdError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/query/sort/{id}'
        });
    }
    
    public static putUmbracoManagementApiV1NoCodeDeliveryApiQuerySortById<ThrowOnError extends boolean = false>(options: Options<PutUmbracoManagementApiV1NoCodeDeliveryApiQuerySortByIdData, ThrowOnError>) {
        return (options?.client ?? client).put<PutUmbracoManagementApiV1NoCodeDeliveryApiQuerySortByIdResponse, PutUmbracoManagementApiV1NoCodeDeliveryApiQuerySortByIdError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/query/sort/{id}'
        });
    }
    
}