// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { PostUmbracoManagementApiV1NoCodeDeliveryApiClientData, PostUmbracoManagementApiV1NoCodeDeliveryApiClientError, PostUmbracoManagementApiV1NoCodeDeliveryApiClientResponse, GetUmbracoManagementApiV1NoCodeDeliveryApiClientError, GetUmbracoManagementApiV1NoCodeDeliveryApiClientResponse, DeleteUmbracoManagementApiV1NoCodeDeliveryApiClientByIdData, DeleteUmbracoManagementApiV1NoCodeDeliveryApiClientByIdError, DeleteUmbracoManagementApiV1NoCodeDeliveryApiClientByIdResponse, PutUmbracoManagementApiV1NoCodeDeliveryApiClientByIdData, PutUmbracoManagementApiV1NoCodeDeliveryApiClientByIdError, PutUmbracoManagementApiV1NoCodeDeliveryApiClientByIdResponse, PostUmbracoManagementApiV1NoCodeDeliveryApiFilterData, PostUmbracoManagementApiV1NoCodeDeliveryApiFilterError, PostUmbracoManagementApiV1NoCodeDeliveryApiFilterResponse, GetUmbracoManagementApiV1NoCodeDeliveryApiFilterError, GetUmbracoManagementApiV1NoCodeDeliveryApiFilterResponse, DeleteUmbracoManagementApiV1NoCodeDeliveryApiFilterByIdData, DeleteUmbracoManagementApiV1NoCodeDeliveryApiFilterByIdError, DeleteUmbracoManagementApiV1NoCodeDeliveryApiFilterByIdResponse, PutUmbracoManagementApiV1NoCodeDeliveryApiFilterByIdData, PutUmbracoManagementApiV1NoCodeDeliveryApiFilterByIdError, PutUmbracoManagementApiV1NoCodeDeliveryApiFilterByIdResponse, PostUmbracoManagementApiV1NoCodeDeliveryApiSortData, PostUmbracoManagementApiV1NoCodeDeliveryApiSortError, PostUmbracoManagementApiV1NoCodeDeliveryApiSortResponse, GetUmbracoManagementApiV1NoCodeDeliveryApiSortError, GetUmbracoManagementApiV1NoCodeDeliveryApiSortResponse, DeleteUmbracoManagementApiV1NoCodeDeliveryApiSortByIdData, DeleteUmbracoManagementApiV1NoCodeDeliveryApiSortByIdError, DeleteUmbracoManagementApiV1NoCodeDeliveryApiSortByIdResponse, PutUmbracoManagementApiV1NoCodeDeliveryApiSortByIdData, PutUmbracoManagementApiV1NoCodeDeliveryApiSortByIdError, PutUmbracoManagementApiV1NoCodeDeliveryApiSortByIdResponse } from './types.gen';

export const client = createClient(createConfig());

export class ClientsService {
    public static postUmbracoManagementApiV1NoCodeDeliveryApiClient<ThrowOnError extends boolean = false>(options?: Options<PostUmbracoManagementApiV1NoCodeDeliveryApiClientData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUmbracoManagementApiV1NoCodeDeliveryApiClientResponse, PostUmbracoManagementApiV1NoCodeDeliveryApiClientError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/client'
        });
    }
    
    public static getUmbracoManagementApiV1NoCodeDeliveryApiClient<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoManagementApiV1NoCodeDeliveryApiClientResponse, GetUmbracoManagementApiV1NoCodeDeliveryApiClientError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/client'
        });
    }
    
    public static deleteUmbracoManagementApiV1NoCodeDeliveryApiClientById<ThrowOnError extends boolean = false>(options: Options<DeleteUmbracoManagementApiV1NoCodeDeliveryApiClientByIdData, ThrowOnError>) {
        return (options?.client ?? client).delete<DeleteUmbracoManagementApiV1NoCodeDeliveryApiClientByIdResponse, DeleteUmbracoManagementApiV1NoCodeDeliveryApiClientByIdError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/client/{id}'
        });
    }
    
    public static putUmbracoManagementApiV1NoCodeDeliveryApiClientById<ThrowOnError extends boolean = false>(options: Options<PutUmbracoManagementApiV1NoCodeDeliveryApiClientByIdData, ThrowOnError>) {
        return (options?.client ?? client).put<PutUmbracoManagementApiV1NoCodeDeliveryApiClientByIdResponse, PutUmbracoManagementApiV1NoCodeDeliveryApiClientByIdError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/client/{id}'
        });
    }
    
}

export class FiltersService {
    public static postUmbracoManagementApiV1NoCodeDeliveryApiFilter<ThrowOnError extends boolean = false>(options?: Options<PostUmbracoManagementApiV1NoCodeDeliveryApiFilterData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUmbracoManagementApiV1NoCodeDeliveryApiFilterResponse, PostUmbracoManagementApiV1NoCodeDeliveryApiFilterError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/filter'
        });
    }
    
    public static getUmbracoManagementApiV1NoCodeDeliveryApiFilter<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoManagementApiV1NoCodeDeliveryApiFilterResponse, GetUmbracoManagementApiV1NoCodeDeliveryApiFilterError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/filter'
        });
    }
    
    public static deleteUmbracoManagementApiV1NoCodeDeliveryApiFilterById<ThrowOnError extends boolean = false>(options: Options<DeleteUmbracoManagementApiV1NoCodeDeliveryApiFilterByIdData, ThrowOnError>) {
        return (options?.client ?? client).delete<DeleteUmbracoManagementApiV1NoCodeDeliveryApiFilterByIdResponse, DeleteUmbracoManagementApiV1NoCodeDeliveryApiFilterByIdError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/filter/{id}'
        });
    }
    
    public static putUmbracoManagementApiV1NoCodeDeliveryApiFilterById<ThrowOnError extends boolean = false>(options: Options<PutUmbracoManagementApiV1NoCodeDeliveryApiFilterByIdData, ThrowOnError>) {
        return (options?.client ?? client).put<PutUmbracoManagementApiV1NoCodeDeliveryApiFilterByIdResponse, PutUmbracoManagementApiV1NoCodeDeliveryApiFilterByIdError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/filter/{id}'
        });
    }
    
}

export class SortersService {
    public static postUmbracoManagementApiV1NoCodeDeliveryApiSort<ThrowOnError extends boolean = false>(options?: Options<PostUmbracoManagementApiV1NoCodeDeliveryApiSortData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUmbracoManagementApiV1NoCodeDeliveryApiSortResponse, PostUmbracoManagementApiV1NoCodeDeliveryApiSortError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/sort'
        });
    }
    
    public static getUmbracoManagementApiV1NoCodeDeliveryApiSort<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoManagementApiV1NoCodeDeliveryApiSortResponse, GetUmbracoManagementApiV1NoCodeDeliveryApiSortError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/sort'
        });
    }
    
    public static deleteUmbracoManagementApiV1NoCodeDeliveryApiSortById<ThrowOnError extends boolean = false>(options: Options<DeleteUmbracoManagementApiV1NoCodeDeliveryApiSortByIdData, ThrowOnError>) {
        return (options?.client ?? client).delete<DeleteUmbracoManagementApiV1NoCodeDeliveryApiSortByIdResponse, DeleteUmbracoManagementApiV1NoCodeDeliveryApiSortByIdError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/sort/{id}'
        });
    }
    
    public static putUmbracoManagementApiV1NoCodeDeliveryApiSortById<ThrowOnError extends boolean = false>(options: Options<PutUmbracoManagementApiV1NoCodeDeliveryApiSortByIdData, ThrowOnError>) {
        return (options?.client ?? client).put<PutUmbracoManagementApiV1NoCodeDeliveryApiSortByIdResponse, PutUmbracoManagementApiV1NoCodeDeliveryApiSortByIdError, ThrowOnError>({
            ...options,
            url: '/umbraco/management/api/v1/no-code-delivery-api/sort/{id}'
        });
    }
    
}