// This file is auto-generated by @hey-api/openapi-ts

export type AddClientRequestModel = {
    name: string;
    origin: string;
    previewUrlPath?: (string) | null;
    publishedUrlPath?: (string) | null;
    culture?: (string) | null;
};

export type AddFilterRequestModel = {
    name: string;
    propertyAliases: Array<(string)>;
    filterMatchType: FilterMatchType;
    primitiveFieldType: PrimitiveFieldType;
};

export type AddSortRequestModel = {
    name: string;
    propertyAlias: string;
    primitiveFieldType: PrimitiveFieldType;
};

export type ClientViewModel = {
    id: string;
    name: string;
    origin: string;
    previewUrlPath?: (string) | null;
    publishedUrlPath?: (string) | null;
    culture?: (string) | null;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type FilterMatchType = 'Exact' | 'Partial';

export type FilterViewModel = {
    id: string;
    name: string;
    alias: string;
    fieldName: string;
    primitiveFieldType: PrimitiveFieldType;
    propertyAliases: Array<(string)>;
    filterMatchType: FilterMatchType;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type OverviewViewModel = {
    filters: Array<(FilterViewModel)>;
    sorts: Array<(SortViewModel)>;
    canAddFilter: boolean;
    canAddSort: boolean;
};

export type PrimitiveFieldType = 'String' | 'Number' | 'Date';

export type SortViewModel = {
    id: string;
    name: string;
    alias: string;
    fieldName: string;
    primitiveFieldType: PrimitiveFieldType;
    propertyAlias: string;
};

export type UpdateClientRequestModel = {
    name: string;
    origin: string;
    previewUrlPath?: (string) | null;
    publishedUrlPath?: (string) | null;
    culture?: (string) | null;
};

export type UpdateFilterRequestModel = {
    name: string;
    propertyAliases: Array<(string)>;
};

export type UpdateSortRequestModel = {
    name: string;
    propertyAlias: string;
};

export type PostUmbracoManagementApiV1NoCodeDeliveryApiClientData = {
    body?: (AddClientRequestModel);
};

export type PostUmbracoManagementApiV1NoCodeDeliveryApiClientResponse = (string);

export type PostUmbracoManagementApiV1NoCodeDeliveryApiClientError = (string | unknown);

export type GetUmbracoManagementApiV1NoCodeDeliveryApiClientResponse = (Array<(ClientViewModel)>);

export type GetUmbracoManagementApiV1NoCodeDeliveryApiClientError = (unknown);

export type DeleteUmbracoManagementApiV1NoCodeDeliveryApiClientByIdData = {
    path: {
        id: string;
    };
};

export type DeleteUmbracoManagementApiV1NoCodeDeliveryApiClientByIdResponse = (string);

export type DeleteUmbracoManagementApiV1NoCodeDeliveryApiClientByIdError = (string | unknown);

export type PutUmbracoManagementApiV1NoCodeDeliveryApiClientByIdData = {
    body?: (UpdateClientRequestModel);
    path: {
        id: string;
    };
};

export type PutUmbracoManagementApiV1NoCodeDeliveryApiClientByIdResponse = (string);

export type PutUmbracoManagementApiV1NoCodeDeliveryApiClientByIdError = (string | unknown);

export type GetUmbracoManagementApiV1NoCodeDeliveryApiQueryResponse = ((OverviewViewModel));

export type GetUmbracoManagementApiV1NoCodeDeliveryApiQueryError = (unknown);

export type PostUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterData = {
    body?: (AddFilterRequestModel);
};

export type PostUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterResponse = (string);

export type PostUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterError = (string | unknown);

export type DeleteUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterByIdData = {
    path: {
        id: string;
    };
};

export type DeleteUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterByIdResponse = (string);

export type DeleteUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterByIdError = (string | unknown);

export type PutUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterByIdData = {
    body?: (UpdateFilterRequestModel);
    path: {
        id: string;
    };
};

export type PutUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterByIdResponse = (string);

export type PutUmbracoManagementApiV1NoCodeDeliveryApiQueryFilterByIdError = (string | unknown);

export type PostUmbracoManagementApiV1NoCodeDeliveryApiQuerySortData = {
    body?: (AddSortRequestModel);
};

export type PostUmbracoManagementApiV1NoCodeDeliveryApiQuerySortResponse = (string);

export type PostUmbracoManagementApiV1NoCodeDeliveryApiQuerySortError = (string | unknown);

export type DeleteUmbracoManagementApiV1NoCodeDeliveryApiQuerySortByIdData = {
    path: {
        id: string;
    };
};

export type DeleteUmbracoManagementApiV1NoCodeDeliveryApiQuerySortByIdResponse = (string);

export type DeleteUmbracoManagementApiV1NoCodeDeliveryApiQuerySortByIdError = (string | unknown);

export type PutUmbracoManagementApiV1NoCodeDeliveryApiQuerySortByIdData = {
    body?: (UpdateSortRequestModel);
    path: {
        id: string;
    };
};

export type PutUmbracoManagementApiV1NoCodeDeliveryApiQuerySortByIdResponse = (string);

export type PutUmbracoManagementApiV1NoCodeDeliveryApiQuerySortByIdError = (string | unknown);