// This file is auto-generated by @hey-api/openapi-ts

export type AddClientRequestModel = {
    name: string;
    origin: string;
    previewUrlPath?: string | null;
    publishedUrlPath?: string | null;
    culture?: string | null;
};

export type AddFilterRequestModel = {
    name: string;
    propertyAliases: Array<string>;
    filterMatchType: FilterMatchTypeModel;
    primitiveFieldType: PrimitiveFieldTypeModel;
};

export type AddSortRequestModel = {
    name: string;
    propertyAlias: string;
    primitiveFieldType: PrimitiveFieldTypeModel;
};

export type ClientModel = {
    id: string;
    name: string;
    origin: string;
    previewUrlPath?: string | null;
    publishedUrlPath?: string | null;
    culture?: string | null;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type FilterListModel = {
    filters: Array<FilterModel>;
    canAddFilter: boolean;
};

export enum FilterMatchTypeModel {
    EXACT = 'Exact',
    PARTIAL = 'Partial'
}

export type FilterModel = {
    id: string;
    name: string;
    alias: string;
    fieldName: string;
    primitiveFieldType: PrimitiveFieldTypeModel;
    propertyAliases: Array<string>;
    filterMatchType: FilterMatchTypeModel;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export enum PrimitiveFieldTypeModel {
    STRING = 'String',
    NUMBER = 'Number',
    DATE = 'Date'
}

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | (string | null) | (string | null) | (number | null) | (string | null) | (string | null) | undefined;
};

export type SortListModel = {
    sorts: Array<SortModel>;
    canAddSort: boolean;
};

export type SortModel = {
    id: string;
    name: string;
    alias: string;
    fieldName: string;
    primitiveFieldType: PrimitiveFieldTypeModel;
    propertyAlias: string;
};

export type UpdateClientRequestModel = {
    name: string;
    origin: string;
    previewUrlPath?: string | null;
    publishedUrlPath?: string | null;
    culture?: string | null;
};

export type UpdateFilterRequestModel = {
    name: string;
    propertyAliases: Array<string>;
};

export type UpdateSortRequestModel = {
    name: string;
    propertyAlias: string;
};

export type GetNoCodeDeliveryApiClientData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/no-code-delivery-api/client';
};

export type GetNoCodeDeliveryApiClientErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetNoCodeDeliveryApiClientResponses = {
    /**
     * OK
     */
    200: Array<ClientModel>;
};

export type GetNoCodeDeliveryApiClientResponse = GetNoCodeDeliveryApiClientResponses[keyof GetNoCodeDeliveryApiClientResponses];

export type PostNoCodeDeliveryApiClientData = {
    body?: AddClientRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/no-code-delivery-api/client';
};

export type PostNoCodeDeliveryApiClientErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type PostNoCodeDeliveryApiClientResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteNoCodeDeliveryApiClientByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/management/api/v1/no-code-delivery-api/client/{id}';
};

export type DeleteNoCodeDeliveryApiClientByIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type DeleteNoCodeDeliveryApiClientByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutNoCodeDeliveryApiClientByIdData = {
    body?: UpdateClientRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/management/api/v1/no-code-delivery-api/client/{id}';
};

export type PutNoCodeDeliveryApiClientByIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type PutNoCodeDeliveryApiClientByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetNoCodeDeliveryApiFilterData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/no-code-delivery-api/filter';
};

export type GetNoCodeDeliveryApiFilterErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetNoCodeDeliveryApiFilterResponses = {
    /**
     * OK
     */
    200: FilterListModel;
};

export type GetNoCodeDeliveryApiFilterResponse = GetNoCodeDeliveryApiFilterResponses[keyof GetNoCodeDeliveryApiFilterResponses];

export type PostNoCodeDeliveryApiFilterData = {
    body?: AddFilterRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/no-code-delivery-api/filter';
};

export type PostNoCodeDeliveryApiFilterErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type PostNoCodeDeliveryApiFilterError = PostNoCodeDeliveryApiFilterErrors[keyof PostNoCodeDeliveryApiFilterErrors];

export type PostNoCodeDeliveryApiFilterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteNoCodeDeliveryApiFilterByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/management/api/v1/no-code-delivery-api/filter/{id}';
};

export type DeleteNoCodeDeliveryApiFilterByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type DeleteNoCodeDeliveryApiFilterByIdError = DeleteNoCodeDeliveryApiFilterByIdErrors[keyof DeleteNoCodeDeliveryApiFilterByIdErrors];

export type DeleteNoCodeDeliveryApiFilterByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutNoCodeDeliveryApiFilterByIdData = {
    body?: UpdateFilterRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/management/api/v1/no-code-delivery-api/filter/{id}';
};

export type PutNoCodeDeliveryApiFilterByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type PutNoCodeDeliveryApiFilterByIdError = PutNoCodeDeliveryApiFilterByIdErrors[keyof PutNoCodeDeliveryApiFilterByIdErrors];

export type PutNoCodeDeliveryApiFilterByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetNoCodeDeliveryApiSortData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/no-code-delivery-api/sort';
};

export type GetNoCodeDeliveryApiSortErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetNoCodeDeliveryApiSortResponses = {
    /**
     * OK
     */
    200: SortListModel;
};

export type GetNoCodeDeliveryApiSortResponse = GetNoCodeDeliveryApiSortResponses[keyof GetNoCodeDeliveryApiSortResponses];

export type PostNoCodeDeliveryApiSortData = {
    body?: AddSortRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/no-code-delivery-api/sort';
};

export type PostNoCodeDeliveryApiSortErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type PostNoCodeDeliveryApiSortError = PostNoCodeDeliveryApiSortErrors[keyof PostNoCodeDeliveryApiSortErrors];

export type PostNoCodeDeliveryApiSortResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteNoCodeDeliveryApiSortByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/management/api/v1/no-code-delivery-api/sort/{id}';
};

export type DeleteNoCodeDeliveryApiSortByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type DeleteNoCodeDeliveryApiSortByIdError = DeleteNoCodeDeliveryApiSortByIdErrors[keyof DeleteNoCodeDeliveryApiSortByIdErrors];

export type DeleteNoCodeDeliveryApiSortByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutNoCodeDeliveryApiSortByIdData = {
    body?: UpdateSortRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/management/api/v1/no-code-delivery-api/sort/{id}';
};

export type PutNoCodeDeliveryApiSortByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type PutNoCodeDeliveryApiSortByIdError = PutNoCodeDeliveryApiSortByIdErrors[keyof PutNoCodeDeliveryApiSortByIdErrors];

export type PutNoCodeDeliveryApiSortByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'https://localhost:44346' | (string & {});
};